require:
  - rubocop/cop/internal_affairs

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile
    - Rakefile