# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.3-node-browsers
        environment:
          TESTOPTS: "--ci-dir=/tmp/test-results"
          APP_ENV: test
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: russa-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: russa-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Run minitest
      - type: shell
        command: bundle exec rake

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results